SELECT 
    UGU.USER_ID, 
    UGU.NICKNAME, 
    SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS UGB 
LEFT JOIN USED_GOODS_USER AS UGU
ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGB.STATUS LIKE 'DONE'
GROUP BY UGU.USER_ID 
HAVING SUM(UGB.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;

-- https://school.programmers.co.kr/learn/courses/30/lessons/164668