SELECT INFO.INGREDIENT_TYPE, 
       SUM(HALF.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS HALF LEFT JOIN ICECREAM_INFO AS INFO
ON HALF.FLAVOR = INFO.FLAVOR
GROUP BY INFO.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;

-- https://school.programmers.co.kr/learn/courses/30/lessons/133026