SELECT BOARD.TITLE, 
       BOARD.BOARD_ID, 
       REPLY.REPLY_ID, 
       REPLY.WRITER_ID, 
       REPLY.CONTENTS, 
       DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS BOARD LEFT JOIN USED_GOODS_REPLY AS REPLY
ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE YEAR(BOARD.CREATED_DATE) = 2022 AND
      MONTH(BOARD.CREATED_DATE) = 10 AND
      REPLY.REPLY_ID IS NOT NULL
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE;

-- https://school.programmers.co.kr/learn/courses/30/lessons/164673