SELECT P.PRODUCT_ID, 
    P.PRODUCT_NAME, 
    SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P LEFT JOIN FOOD_ORDER AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
-- WHERE O.PRODUCE_DATE LIKE '2022-05%'
WHERE YEAR(O.PRODUCE_DATE) = 2022 
    AND MONTH(O.PRODUCE_DATE) = 5
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC

-- https://school.programmers.co.kr/learn/courses/30/lessons/131117